apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: santosh-barai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: ostad
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: ostad
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
